# Copyright (c) 2022 The ZMK Contributors
# SPDX-License-Identifier: MIT

CONFIG_LOG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y

CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

# LEDs - Not sure if will use PWM to control them
CONFIG_LED=y
CONFIG_PWM=y

# For nPM1300 and Touchpad
CONFIG_I2C=y

# Enable shell with many features for debugging
# Turn off for production firmware
CONFIG_SHELL=y
CONFIG_I2C_SHELL=y
CONFIG_GPIO_SHELL=y
CONFIG_LED_SHELL=y
CONFIG_PWM_SHELL=y
CONFIG_SENSOR_SHELL=y
CONFIG_CBPRINTF_COMPLETE=y

CONFIG_INPUT=y
CONFIG_ZMK_HID_TOUCHPAD=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_HID_INDICATORS=y

#CONFIG_BUILD_OUTPUT_UF2=y
