#!/usr/bin/env python3
"""Turn a PixArt FWHD touchpad firmware file into a C include for the keyboard.

Layout (fwupd plugins/pixart-tp/fu-pixart-tp.rs, FuStructPixartTpFirmwareHdr):

    0x000  magic          "FWHD"
    0x004  header_len     u16  0x218
    0x006  header_ver     u16
    0x008  file_ver       u16  e.g. 0x1204
    0x00a  ic_part_id     u16  0x0360
    0x00c  flash_sectors  u16
    0x00e  file_crc32     u32  CRC32 of everything after the header
    0x012  num_sections   u16
    0x014  section headers, 64 B each:
             update_type u8, update_info u8 (bit0 valid, bit1 external),
             target_flash_start u32, internal_file_start u32,
             section_length u32, section_crc u32, shared[12], extname[34]
    0x214  header_crc32   u32  CRC32 of bytes 0..0x214
    0x218  payload (flat flash image; file offset = 0x218 + flash address)

The header and file CRCs are standard CRC32 and are checked here. The
section CRCs are whatever the pad's own CRC engine computes; fwupd never
checks them against the data either, it only compares the pad's result to
them after programming. They are passed through for that comparison.

Only VALID, non-EXTERNAL sections of type 1 (FW) and 3 (PARAM) are emitted,
in file order, which is the order fwupd writes them.
"""

import argparse
import struct
import sys
import zlib

HDR_LEN = 0x218
SEC_HDR_OFF = 0x14
SEC_HDR_LEN = 64
TYPE_FW = 1
TYPE_PARAM = 3
INFO_VALID = 1 << 0
INFO_EXTERNAL = 1 << 1


def die(msg):
    sys.exit(f"gen_tp_fw.py: {msg}")


def parse(data):
    if data[:4] != b"FWHD":
        die("not an FWHD file")
    (header_len, header_ver, file_ver, part_id, flash_sectors, file_crc,
     num_sections) = struct.unpack_from("<HHHHHIH", data, 4)
    if header_len != HDR_LEN:
        die(f"header_len 0x{header_len:x}, expected 0x{HDR_LEN:x}")
    if len(data) < HDR_LEN:
        die("file shorter than its header")
    stored = struct.unpack_from("<I", data, HDR_LEN - 4)[0]
    calc = zlib.crc32(data[: HDR_LEN - 4]) & 0xFFFFFFFF
    if stored != calc:
        die(f"header CRC mismatch: stored 0x{stored:08x} computed 0x{calc:08x}")
    calc = zlib.crc32(data[HDR_LEN:]) & 0xFFFFFFFF
    if file_crc != calc:
        die(f"file CRC mismatch: stored 0x{file_crc:08x} computed 0x{calc:08x}")
    if SEC_HDR_OFF + num_sections * SEC_HDR_LEN > HDR_LEN - 4:
        die(f"{num_sections} sections do not fit in the header")

    sections = []
    for i in range(num_sections):
        off = SEC_HDR_OFF + i * SEC_HDR_LEN
        (utype, uinfo, flash_start, file_start, length,
         crc) = struct.unpack_from("<BBIIII", data, off)
        if not (uinfo & INFO_VALID) or (uinfo & INFO_EXTERNAL):
            continue
        if utype not in (TYPE_FW, TYPE_PARAM):
            die(f"section {i}: unsupported update type {utype}")
        if file_start < HDR_LEN or file_start + length > len(data):
            die(f"section {i}: data 0x{file_start:x}+{length} outside the file")
        if file_start - HDR_LEN != flash_start:
            die(f"section {i}: file offset 0x{file_start:x} is not header+flash "
                f"0x{flash_start:x}; the flat-image assumption is broken")
        if flash_start % 4096:
            die(f"section {i}: flash start 0x{flash_start:x} not sector aligned")
        if length == 0:
            die(f"section {i}: empty")
        sections.append((utype, flash_start, length, crc, data[file_start:file_start + length]))

    types = [s[0] for s in sections]
    if types.count(TYPE_FW) != 1 or types.count(TYPE_PARAM) != 1:
        die(f"expected exactly one FW and one PARAM section, got types {types}")
    return file_ver, part_id, sections


def emit(out, src_name, file_ver, part_id, sections):
    w = out.write
    w("/* Generated by gen_tp_fw.py from %s -- do not edit.\n" % src_name)
    w(" * Included by touchpad_update.c; needs <pixart_tp_update.h>. */\n\n")
    names = {TYPE_FW: "fw", TYPE_PARAM: "param"}
    for utype, flash_start, length, crc, blob in sections:
        w("static const uint8_t tp_fw_%s_data[%d] = {\n" % (names[utype], length))
        for i in range(0, length, 16):
            w("    " + ", ".join("0x%02x" % b for b in blob[i:i + 16]) + ",\n")
        w("};\n\n")
    w("static const struct pixart_tp_fw_section tp_fw_sections[] = {\n")
    for utype, flash_start, length, crc, blob in sections:
        w("    {\n")
        w("        .type = %d,\n" % utype)
        w("        .flash_start = 0x%08x,\n" % flash_start)
        w("        .crc = 0x%08x,\n" % crc)
        w("        .data = tp_fw_%s_data,\n" % names[utype])
        w("        .len = sizeof(tp_fw_%s_data),\n" % names[utype])
        w("    },\n")
    w("};\n\n")
    w("static const struct pixart_tp_fw_image daisy_touchpad_fw_image = {\n")
    w("    .version = 0x%04x,\n" % file_ver)
    w("    .part_id = 0x%04x,\n" % part_id)
    w("    .sections = tp_fw_sections,\n")
    w("    .num_sections = %d,\n" % len(sections))
    w("};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("output")
    ap.add_argument("--part-id", type=lambda x: int(x, 0), default=0x0360)
    args = ap.parse_args()
    with open(args.input, "rb") as f:
        data = f.read()
    file_ver, part_id, sections = parse(data)
    if part_id != args.part_id:
        die(f"file is for part 0x{part_id:04x}, expected 0x{args.part_id:04x}")
    with open(args.output, "w") as out:
        emit(out, args.input.rsplit("/", 1)[-1], file_ver, part_id, sections)
    total = sum(s[2] for s in sections)
    print(f"gen_tp_fw.py: version 0x{file_ver:04x} part 0x{part_id:04x}, "
          f"{len(sections)} sections, {total} bytes", file=sys.stderr)


if __name__ == "__main__":
    main()
